### PR TITLE
update clangd version

### PR DESCRIPTION
**Pull request by uyha**

### CODE REVIEW

**Review by williamboman — COMMENTED** [review]
Hello! The latest stable clangd release is still 16.0.2. I'm not sure why they haven't provided releases for subsequent llvm versions.

**Comment by uyha** [comment]
but i see https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.6 as the release for 16.0.6, or are you talking about something else?

**Comment by uyha** [comment]
oh wait, i mistake llvm and clangd, sorry for that

**Comment by williamboman** [comment]
It might be worthwhile asking them why there's no recent releases after 16.0.2.

**Pull request closed without merging**
