### PR TITLE
feat: add actions-languageserver lsp

### LINKED ISSUE #2377: GitHub Actions Language Server
[GitHub Actions Language Server](https://github.com/actions/languageservices/tree/main/languageserver) provides accurate diagnostics and completions for Workflows files, more than the generic YAML Language Server with JSON schema support, including support for [contexts](https://docs.github.com/en/actions/learn-github-actions/contexts) and [expressions](https://docs.github.com/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions).

For example:

Given a problematic GitHub Workflow yaml, like this:
 
```yaml
1 | jobs:
2 |   job1:
3 |     runs-on: ubuntu-latest
4 |     outputs:
5 |       job1-output: ${{ steps.step1.outputs.some-output }}
6 |     steps:
7 |       - uses: action/checkout@v3
8 |       - id: step-1
9 |         uses: andstor/file-existence-action@v2
10|         with:
11|           files: "**/*.tf"
```

- `yaml-language-server` will not highlight any errors
- `actions/languageserver` will highlight the errors on line 5 (`step1` should be `step-1`) and line 7 (`action/checkout@v3` should be `actions/checkout@v3`)

### PR DESCRIPTION
**Pull request by pbnj**
Closes #2377

### CODE REVIEW

**Comment by pbnj** [comment]
Actually, hold off on this. The npm package `@actions/languageserver` does not provide a binary, but instead provides TypeScript types and compiled ECMAScript modules.

**Comment by williamboman** [comment]
Alright, feel free to ping me again when it's ready :+1:

**Comment by fredrikaverpil** [comment]
@pbnj this would be a great to have. What was the blocker here?

**Comment by pbnj** [comment]
@fredrikaverpil - This is the blocker: https://github.com/actions/languageservices/issues/56

**Pull request closed without merging**
