### PR TITLE
Feat: Agda Language Server

### LINKED ISSUE #3936: agda-language-server
Agda has an official language server: https://github.com/agda/agda-language-server

### PR DESCRIPTION
**Pull request by foxyseta**
## Describe your changes

Add Agda-Language-Server. It appears the VSCode package manifest uses yaml rather than json, which seems not to be supported by Mason apparently.

## Issue ticket number and link
Closes #3936.
Old PR: #3972

## Checklist before requesting a review

- [x] I have successfully tested installation of the package.
- [x] I have successfully tested the package after installation.

### CODE REVIEW

**Comment by foxyseta** [comment]
Not sure how to manage having a `package.yaml` rather than a `package.json` @williamboman

**Comment by foxyseta** [comment]
Opened related PR in nvim-lspconfig: https://github.com/neovim/nvim-lspconfig/pull/3100

**Comment by foxyseta** [comment]
https://github.com/neovim/nvim-lspconfig/pull/3100 (by me) got merged, so `nvim-lspconfig` already supports this LS.

**Comment by williamboman** [comment]
Hey and thanks for the PR (and sorry for late review)! Custom build scripts are being deprecated because of difficulty in maintaining them over time and their common reliance on system dependencies that Mason cannot detect. You can always host your own registry if you'd like to manage it through Mason, see https://github.com/williamboman/mason-registry-playground/ for a starting point

**Comment by foxyseta** [comment]
Thank you! This package is now available at [`visimp`'s Mason registry](https://github.com/visimp/mason-registry) as `agda_ls`.

**Pull request closed without merging**
