### PR TITLE
Support markdown oxide binaries

### PR DESCRIPTION
**Pull request by Feel-ix-343**
Are the platforms typical? How does this look at @williamboman

### CODE REVIEW

**Comment by Feel-ix-343** [comment]
Hey I am also noticing that the binaries are a significantly slower than compiling from source. Is this typical?

**Comment by Feel-ix-343** [comment]
I fixed it by changing the linux rustc target. Very fast now

**Comment by Feel-ix-343** [comment]
Hey @williamboman I am a highschooler trying to update my waitlist colleges with this project. Rigth now, nobody without rust can use it, and this is blocking to my publishing of the project. I really want to share a great update with stats and details from publishing the project, but the deadline is in about a week. Would you mind reviewing this soon so I can publish?

Thank you

**Review by williamboman — APPROVED** [review]
Thanks!

**Pull request merged**
