### PR TITLE
feat: add slides

### PR DESCRIPTION
**Pull request by pbnj**

### CODE REVIEW

**Review by williamboman — COMMENTED** [review]
Hey & thanks for the PR! I fail to see how this is related to Neovim though. Packages in the core registry must have a clear link to Neovim.

**Comment by pbnj** [comment]
This is similar to Glow.

**Comment by williamboman** [comment]
Glow being added was justified by it being integrated in Neovim via for example https://github.com/ellisonleao/glow.nvim. Is there something similar for slides?

**Comment by pbnj** [comment]
@williamboman - https://github.com/aspeddro/slides.nvim

**Comment by williamboman** [comment]
Hmm I'm really on the fence about this one. I don't want to saturate the registry with packages it's not (at least yet) intended for. I really fail to see a fundamental connection to Neovim workflows. Is this solely a matter of making it available for installation via Mason for external usage or are there a somewhat broadly employed workflow of incorporating slides in Neovim (e.g. via builtin terminal)?

**Comment by pbnj** [comment]
That's ok.

I will close this PR.

If more folks come across this in the future, they may express interest by commenting or resubmitting the PR.

**Pull request closed without merging**
