### PR TITLE
feat(nimlsp): use nimsuggest on system

### PR DESCRIPTION
**Pull request by walker27460**
This will let build process use nimsuggest provided on system.

### CODE REVIEW

**Comment by williambotman** [comment]
@mason-org/triage `notify(Reason::NewPullRequest)`

<sup>This comment ensures a notification is delivered to maintainers.</sup>

<sup>` 🤖 This is an automated comment. `  [` 📖 Source code `](https://github.com/williamboman/botman)</sup>

**Comment by walker27460** [comment]
It seems not.
Nim installed from Homebrew fails for me.
Try testing with choosenim.
Marking draft due to above.

**Comment by williamboman** [comment]
Actually, the failing test seems to have been due to external factors. CI seems to pass, I'm happy to merge this as-is unless you want to investigate further?

**Comment by walker27460** [comment]
I couldn't figure out so closed this for now.

**Pull request closed without merging**
