### PR TITLE
feat: add flowjs

### PR DESCRIPTION
**Pull request by mickro**
WIP

This PR aims to add flowjs to Mason.

TO CHECK:
- global syntax
- how to use the project version of flow instead of the latest?
  - "${workspaceFolder}/node_modules/.bin/flow"

useful links:
- https://flow.org/en/docs/install/
- https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode

### CODE REVIEW

**Comment by mickro** [comment]
... the PR is stuck. How to move forward ?

**Review by williamboman — COMMENTED** [review]
Hello and thanks for the PR! Flow should generally be installed and ran locally in each project, is there any reason you want to add it here as well?

**Comment by mickro** [comment]
> Hello and thanks for the PR! Flow should generally be installed and ran locally in each project, is there any reason you want to add it here as well?

Thanks for the reply.  My point is to make the support of _flow js_ easier.

I am pretty new on `nvim`. I found that managing any LSP language via `manson` really easy to use. But flow js is missing in the list.

Later I managed to read and apply correctly the documentation from `nvim-lspconfig` about _flow js_:
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#flow

However I believe that it will be really great to manage _flow js_ as other via `manson` interface.

**Comment by williamboman** [comment]
Closing this [as official docs recommends installing it per-project](https://flow.org/en/docs/install/), thanks for the PR anyways!

**Pull request closed without merging**
