### PR TITLE
fix(harper-ls): change filename to `-msvc` from `-gnu`

### PR DESCRIPTION
**Pull request by elijah-potter**
## Describe your changes
We've added some additional language support and changed our target compiler architecture. This PR fixes the broken filename and highlights this language support.

### CODE REVIEW

**Comment by elijah-potter** [comment]
@williamboman is there anything I need to do to get this merged? I've got users who need this as soon as possible.

**Comment by elijah-potter** [comment]
Just wanted to nudge again to see if there's anything I can do to get this merged @williamboman or @chrisgrieser

**Comment by chrisgrieser** [comment]
@elijah-potter Looks good to me, I've been using this package spec in my personal config (manually added) already: https://github.com/chrisgrieser/.config/blob/main/nvim/personal-mason-registry/packages/harper-ls/package.yaml

I think this PR not being merged isn't due to the changes, but simply due to the maintainer not being available. There are 150+ open PRs, after all. Unfortunately, I am just an occasional contributor and do not have the rights to merge anything in this repo (otherwise, I'd have done so already).

**Comment by elijah-potter** [comment]
@chrisgrieser is see. That makes sense. Hopefully he sees this soon :crossed_fingers:. We've got a lot of improvements that I can't push out yet because of this.

**Comment by chrisgrieser** [comment]
>  We've got a lot of improvements that I can't push out yet because of this.

@elijah-potter If this is about a new release, then you can still go for it. People can still install harper-ls manually or via a personal mason registry (like I do). As I harper-user I am looking forward to some improvements myself 😋

**Comment by DYnamoX513** [comment]
Any update on this? Why doesn't the Renovate bot pick up the update from harper-ls? 🤔

**Review by williamboman — APPROVED** [review]
Thanks!

**Pull request merged**
