### PR TITLE
feat: add nextls

### PR DESCRIPTION
**Pull request by jared-mackey**
Hi!

First time making one of these. Please let me know of any adjustments needed. I have not been able to test it yet since I am not sure how. Will be working through that while this PR is open.

### CODE REVIEW

**Review by williamboman — COMMENTED** [review]
The package definition looks good to me! However, the file that gets downloaded is just a small Elixir script that in turn calls into Mix to install the nextls language server (presumably globally, i.e. outside of Mason), and then starts it. This makes it not a particularly good fit for Mason because it won't really be installing anything via Mason, or rather it will install an install script, which is kinda weird.

**Comment by mhanberg** [comment]
Hi!

NextLS author here. 

I completely agree with what you've said here, and have tried to explain that mason is not as useful here, but...

eventually (in the coming months maybe) I hope to distribute NextLS as a compiler binary, rather than a bootstrapping script. 

So, Mason would be useful then, and I think the mason registry here wouldn't need to change. 

I plan on still having my plugins (neovim, vscode, etc) downloading it for you, but some people prefer mason. 

I hope that helps in your calculus on whether to include NextLS in the registry.

**Comment by williamboman** [comment]
@mhanberg Cool I had some issues with the Burrito wrapper on Ubuntu 20.04, it pulled binaries linked to glibc 2.34 (quite recent release) so I couldn't execute it. Not sure if it's a Burrito issue or nextls issue though.

**Comment by mhanberg** [comment]
That's a burrito thing. 

I'm not sure if there is a way to lower it but I'll talk to the burrito author. 

He was working on embedding musl statically instead of dynamic linking so that might make it easier to support older operating systems.

**Comment by mhanberg** [comment]
@williamboman is that a blocker? Just for clarity, if I need to get it to work on older operating systems.

**Comment by williamboman** [comment]
Hey sorry I got distracted while reviewing this, forgot about this.

My final thought was about the name, I'm leaning towards `nextls` (or `next_ls` or `next-ls`), wdyt? It might cause people to think it's related to Next.js but I think the description and language mapping makes up for that. Also, what is the canonical binary name, `nextls` or `next_ls`?

**Comment by mhanberg** [comment]
@williamboman no worries at all.

let's go with `nextls` for name and binary

**Comment by mhanberg** [comment]
Thanks!

@jared-mackey  let me know if you get a moment to try this out

**Pull request merged**
