### PR TITLE
bump(sonarlint-language-server): update to v4.14.0

### PR DESCRIPTION
**Pull request by coderkun**
Update SonarLint language server to version [4.14](https://github.com/SonarSource/sonarlint-vscode/releases/tag/4.14.0%2B77092).

### CODE REVIEW

**Comment by tcordel** [comment]
Highly expected fixed du to last pr introducing a bug in which sonarlint LSP was not working anymore
https://gitlab.com/schrieveslaach/sonarlint.nvim/-/issues/24#note_2219997581

**Review by schrieveslaach — APPROVED** [review]
Tested this change locally with the [testing instructions](https://github.com/mason-org/mason-registry/blob/main/CONTRIBUTING.md#testing) and works great.

**Comment by schrieveslaach** [comment]
3.14.0.75765 is out.

**Comment by coderkun** [comment]
> 3.14.0.75765 is out.

We still need to wait for SonarLint VSCode to be released.

Do you think I should push another commit to this PR or create a new, independent PR?

**Comment by metal3d** [comment]
4.14.0 is now out. Sonarlint extension fails with 4.11 version, can you please update?

**Comment by schrieveslaach** [comment]
> We still need to wait for SonarLint VSCode to be released.

Usually, the update of VScode follows shortly. [4.14.0+77092](https://github.com/SonarSource/sonarlint-vscode/releases/tag/4.14.0%2B77092) is already available.

> Do you think I should push another commit to this PR or create a new, independent PR?

I don't know the best practice of the Mason people. None of the maintainers responded yet. Thus, I would create a new commit and maybe squash all of them into one. But that's just my humble opinion. :shrug:

**Comment by coderkun** [comment]
I pushed the update to 4.14.0, squashed the commits and rebased the branch ontop of the latest main.

**Comment by metal3d** [comment]
> I don't know the best practice of the Mason people. None of the maintainers responded yet. Thus, I would create a new commit and maybe squash all of them into one. But that's just my humble opinion. 🤷

I wonder if there could not be another way to automate registry when newest version of (some) packages should be updated here. Maybe a GH action, periodic, can help.

**Comment by coderkun** [comment]
> I wonder if there could not be another way to automate registry when newest version of (some) packages should be updated here. Maybe a GH action, periodic, can help.

The already use Renovate to automate most of the updates. But SonarLint uses a non-standard versioning scheme which does not allow to automate it (or makes it harder, at least).

**Review by williamboman — APPROVED** [review]
Thanks!

**Pull request merged**
