### PR TITLE
feat: add protols LSP for protobuf

### PR DESCRIPTION
**Pull request by coder3101**
## Describe your changes

Add an LSP for protocol buffer with support for:

- Hover
- Diagnostics
- Go to Definition
- Rename
- Completion

Originally: https://github.com/coder3101/protols

## Checklist before requesting a review

- [x] I have successfully tested installation of the package.
- [x] I have successfully tested the package after installation.

### CODE REVIEW

**Comment by coder3101** [comment]
https://github.com/neovim/nvim-lspconfig/pull/3219

**Comment by coder3101** [comment]
@williamboman could you please take a look at this.

**Comment by mvillafuertem** [comment]
@williamboman  @coder3101 any update? thanks

**Review by williamboman — APPROVED** [review]
Thanks!

**Pull request merged**
