### PR TITLE
Upgrade the gitui to 0.26.3

### PR DESCRIPTION
**Pull request by adamma1024**
## Describe your changes
I've created an issue recently, but I found it's gitui's fault. Their 0.26.2 doesn't work on darwin_x64. #7260

I noticed the upgrading of gitui was failed #5956 , so I upgraded the gitui to 0.26.3 and solved this issue.

## Issue ticket number and link
#7260 
#5956 

## Checklist before requesting a review
- [x] I have successfully tested installation of the package.
- [x] I have successfully tested the package after installation.

## Screenshots
image
image
image

### CODE REVIEW

**Comment by adamma1024** [comment]
Hi guys, I'm not sure if it's enough. Let me know if I still need to do something. I'm glad to contribute such a meaningful project with you all.

**Comment by adamma1024** [comment]
Hi, is there anyone can help review? Appreciate so much.

**Comment by adamma1024** [comment]
bump

**Comment by adamma1024** [comment]
> I would rebase your fork and then merge it into main instead of that renovate branch, so you don't repeat all the previous commits and that after the merge it's in main so everybody has it.

No problem. Thank you.

**Review by williamboman — APPROVED** [review]
Thanks! I updated the merge base and fixed the version overrides (we need 2 of them to support versions `>0.25.2 <=0.26.2`)

**Pull request merged**
