### PR TITLE
Prolog LSP server

### LINKED ISSUE #3935: Prolog LS
Prolog LSP server: https://github.com/jamesnvc/lsp_server
Could we add this maybe?

### PR DESCRIPTION
**Pull request by foxyseta**
## Describe your changes

Add the Prolog Language Server.

## Issue ticket number and link
Closes #3935.

## Checklist before requesting a review

- [x] I have successfully tested installation of the package.
- [x] I have successfully tested the package after installation.

### CODE REVIEW

**Comment by foxyseta** [comment]
Bump

**Review by williamboman — COMMENTED** [review]
Thanks for the PR! Same concerns as in https://github.com/mason-org/mason-registry/pull/4009#pullrequestreview-1940791128. It seems like package installation happens "globally". [For running the server it seems this global installation is imported and executed via swipl](https://github.com/jamesnvc/lsp_server?tab=readme-ov-file#vimneovim).

[`pack_install\2`](https://www.swi-prolog.org/pldoc/doc_for?object=pack_install/2) seems like it maybe supports "local" installations, but I'm not sure what potential implications of doing that would be (e.g. how would one execute it, would a wrapper script necessary?)

**Comment by foxyseta** [comment]
We are talking about

> pack_directory(+Dir)
>    Directory into which to install the package.

right? The wrapper script would be this one https://github.com/jamesnvc/lsp_server#native-lsp-for-neovim--05,
which I would need to edit according to the path of the local installation. Are there any reference examples?

**Comment by foxyseta** [comment]
@williamboman how does this look? The installation should now be local. The LS's author specifies the flags to be used in the README, so I am currently creating the wrapper script on the fly.

Could not find relevant examples in docs so I am currently puzzled at this stack trace:

```
Error executing luv callback:
bad argument #2 to '?' (data must be string or table of strings, got nil)
stack traceback:
        [C]: in function 'error'
        ...e/pack/paks/opt/mason.nvim/lua/mason-core/async/init.lua:113: in function 'callback'
        ...e/pack/paks/opt/mason.nvim/lua/mason-core/async/init.lua:91: in function 'cb'
        ...e/pack/paks/opt/mason.nvim/lua/mason-core/async/init.lua:21: in function 'reject'
        ...e/pack/paks/opt/mason.nvim/lua/mason-core/async/init.lua:62: in function 'resolver'
        ...e/pack/paks/opt/mason.nvim/lua/mason-core/async/init.lua:26: in function 'promise_or_result'
        ...e/pack/paks/opt/mason.nvim/lua/mason-core/async/init.lua:81: in function 'cb'
        ...e/pack/paks/opt/mason.nvim/lua/mason-core/async/init.lua:21: in function 'resolve'
        ...e/pack/paks/opt/mason.nvim/lua/mason-core/async/init.lua:54: in function <...e/pack/paks/opt/mason.nvim/lua/mason-core/async/init.lua:50>
Press ENTER or type command to continue
```
Is there a way to see the rest of the frames?

**Comment by foxyseta** [comment]
> Thanks for the PR! Same concerns as in [#4009 (review)](https://github.com/mason-org/mason-registry/pull/4009#pullrequestreview-1940791128). It seems like package installation happens "globally". [For running the server it seems this global installation is imported and executed via swipl](https://github.com/jamesnvc/lsp_server?tab=readme-ov-file#vimneovim).
> 
> [`pack_install\2`](https://www.swi-prolog.org/pldoc/doc_for?object=pack_install/2) seems like it maybe supports "local" installations, but I'm not sure what potential implications of doing that would be (e.g. how would one execute it, would a wrapper script necessary?)

Thanks! Package installation is now local. A one-liner wrapper is now available as a share artifact across all architectures. Is this okay?

**Comment by williamboman** [comment]
Hey and thanks for the PR (and sorry for very late review)! I've been holding off with this PR because custom build scripts are being deprecated because of difficulty in maintaining them over time and their common reliance on system dependencies that Mason cannot detect. You can always host your own registry if you'd like to manage it through Mason, see https://github.com/williamboman/mason-registry-playground/ for a starting point

**Comment by foxyseta** [comment]
This package was released on [`visimp`'s Mason registry] as `prolog_ls`.

**Pull request closed without merging**
