### PR TITLE
Add support for Markdown Oxide

### PR DESCRIPTION
**Pull request by Feel-ix-343**
Related to https://github.com/Feel-ix-343/markdown-oxide/issues/1

### CODE REVIEW

**Comment by chrisgrieser** [comment]
Just a heads-up: releasing binaries is somewhat preferable for mason packages. When the user does not have the rust toolchain installed, they will not be able to install this package:
Pasted image 2024-03-05 at 11 20 31@2x

**Review by williamboman — APPROVED** [review]
Thanks! I modified the source definition to leverage cargo's builtin support for installations from remote git repositories.

**Comment by Feel-ix-343** [comment]
This is great!

And eventually the LS will have a binary. However, things are changing so fast. 

Also @williamboman, with the changes you made, how will new versions be released? Will it happen just when I push a tag?

**Comment by williamboman** [comment]
> Also @williamboman, with the changes you made, how will new versions be released? Will it happen just when I push a tag?

Yeah it'll track tags in the provided GitHub repository.

**Comment by Feel-ix-343** [comment]
Note: I made a PR in mason-lspconfig, too.

**Pull request merged**
